// Import necessary functions from the Redux Toolkit library
import { createSlice } from "@reduxjs/toolkit";

// Create a slice for managing loading alerts
const alertsSlice = createSlice({
  // Name of the slice
  name: "alerts",

  // Initial state of the slice
  initialState: {
    loading: false,
  },

  // Reducers define how the state should be updated in response to actions
  reducers: {
    // Action to show loading state
    ShowLoading: (state, action) => {
      state.loading = true;
    },

    // Action to hide loading state
    HideLoading: (state, action) => {
      state.loading = false;
    },
  },
});

// Export the actions generated by the slice
export const { ShowLoading, HideLoading } = alertsSlice.actions;

// Export the reducer function to be used in the Redux store
export default alertsSlice.reducer;
